apiVersion: apps/v1
kind: Deployment
metadata:
  name: face-crop
  labels:
    app: face-crop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: face-crop
  template:
    metadata:
      labels:
        app: face-crop
    spec:
      containers:
      - name: face-crop
        image: face-crop
        imagePullPolicy: Always   
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
