apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CiAgICAgICJ1c2VybmFtZSI6ICJ6YWluYWIyMTEiLAogICAgICAicGFzc3dvcmQiOiAiZGNrcl9wYXRfQU9fRWlyYzRqWnZxOHZ3YlctSFB4SGI5YS04IiwKICAgICAgImVtYWlsIjogInphaW5hYi56dWxmaXFhcjIxMUBnbWFpbC5jb20iCiAgICB9CiAgfQp9Cgo=

