name: Terraform

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: development
    env:
      AMI_ID: ${{ vars.AMI_ID }}
      REGION: ${{ vars.REGION }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init -upgrade
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Create terraform.auto.tfvars
        working-directory: ./terraform
        env:
         AMI_ID: ${{ vars.AMI_ID }} 
         REGION: ${{ vars.REGION }}
        run: |
          echo "vpc_cidr_block = \"${{ secrets.VPC_CIDR_BLOCK }}\"" > terraform.auto.tfvars
          echo "private_subnet_cidr_blocks = [\"$(echo -n "${{ secrets.PRIVATE_SUBNET_CIDR_BLOCKS }}" | tr -d '\n' | sed 's/,/","/g')\"]" >> terraform.auto.tfvars
          echo "public_subnet_cidr_blocks = [\"$(echo -n "${{ secrets.PUBLIC_SUBNET_CIDR_BLOCKS }}" | tr -d '\n' | sed 's/,/","/g')\"]" >> terraform.auto.tfvars
          echo "ami_id = \"$AMI_ID\"" >> terraform.auto.tfvars
          echo "region = \"$REGION\"" >> terraform.auto.tfvars 

      - name: Terraform Validate
        working-directory: ./terraform
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

     

      - name: Terraform Apply
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        working-directory: ./terraform
        run: terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

     
          
